trigger:
  branches:
    include:
      - master
  tags:
    include:
      - v*

resources:
  repositories:
    - repository: pipelineTemplates
      type: git
      name: Verix/DevOps.PipelineTemplates
      ref: refs/heads/main

variables:
- name: buildConfiguration
  value: 'Release'
- name: DotNetSdkVersion
  value: '10.0.x'
- name: projectPath
  value: 'ContentTower/ContentTower.csproj'
- name: artifactName
  value: 'drop'
- name: publishFolder
  value: '$(Build.ArtifactStagingDirectory)/publish'

stages:
- stage: BuildContainer
  displayName: Build container
  dependsOn: []
  jobs:
    - job: Build
      displayName: Build and push container
      pool:
        vmImage: ubuntu-latest
      
      steps:
        - template: templates/docker-build-push.yml@pipelineTemplates
          parameters:
            dotNetSdkVersion: $(DotNetSdkVersion)
            buildConfiguration: $(buildConfiguration)
            projectPath: $(projectPath)
            targetDockerimage: "verix.contenttower"

- stage: Build
  displayName: 'Build and publish'
  jobs:
  - job: Build
    displayName: 'Build Web API'
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - checkout: self

    - task: UseDotNet@2
      displayName: 'Install .NET SDK'
      inputs:
        packageType: 'sdk'
        version: '10.x'

    - task: DotNetCoreCLI@2
      displayName: 'Restore packages'
      inputs:
        command: 'restore'
        projects: '$(projectPath)'

    - task: DotNetCoreCLI@2
      displayName: 'Build solution'
      inputs:
        command: 'build'
        projects: '$(projectPath)'
        arguments: '--configuration $(buildConfiguration) --no-restore'

    - task: DotNetCoreCLI@2
      displayName: 'Run tests'
      inputs:
        command: 'test'
        projects: '**/ContentTower.Tests/*.csproj'
        arguments: '--configuration $(buildConfiguration)'
      continueOnError: false

    - task: DotNetCoreCLI@2
      displayName: 'Publish Web API'
      inputs:
        command: 'publish'
        publishWebProjects: false
        projects: '$(projectPath)'
        arguments: '--configuration $(buildConfiguration) --output $(publishFolder) --no-build'
        zipAfterPublish: true
        modifyOutputPath: false

    - publish: '$(publishFolder)'
      displayName: 'Publish pipeline artifact'
      artifact: '$(artifactName)'

- stage: Deploy_Dev
  displayName: 'Deploy to IIS Dev'
  dependsOn: Build
  condition: succeeded()

  variables:
  - group: Verix.ContentTower_DEV
  - name: Release.EnvironmentName
    value: 'Development'

  jobs:
  - deployment: DeployToIisDev
    displayName: 'Deploy Web API to IIS Dev'
    environment:
      name: 'Development'
      resourceType: VirtualMachine

    strategy:
      runOnce:
        deploy:
          steps:
          - powershell: |
              Remove-Item "$(Pipeline.Workspace)\$(artifactName)" -Recurse -Force -ErrorAction SilentlyContinue
            displayName: 'Clean downloaded artifact folder'

          - download: current
            artifact: '$(artifactName)'

          - task: IISWebAppManagementOnMachineGroup@0
            displayName: 'Ensuring IIS Website'
            inputs:
              IISDeploymentType: 'IISWebsite'
              ActionIISWebsite: 'CreateOrUpdateWebsite'
              WebsiteName: '$(iisSiteName)'
              WebsitePhysicalPath: '$(iisPhysicalPath)'
              WebsitePhysicalPathAuth: 'WebsiteUserPassThrough'
              AddBinding: true
              Bindings: |
                $(iisBindings)
              CreateOrUpdateAppPoolForWebsite: true
              AppPoolNameForWebsite: '$(iisAppPoolName)'
              DotNetVersionForWebsite: 'No Managed Code'
              PipeLineModeForWebsite: 'Integrated'
              AppPoolIdentityForWebsite: 'ApplicationPoolIdentity'

          - task: IISWebAppDeploymentOnMachineGroup@0
            displayName: 'Deploy files to IIS'
            inputs:
              WebSiteName: '$(iisSiteName)'
              Package: '$(Pipeline.Workspace)/$(artifactName)/**/*.zip'
              TakeAppOfflineFlag: true
              XmlTransformation: true
              XmlVariableSubstitution: true
              JSONFiles: |
                **/appsettings.Development.json

- stage: Deploy_Acc
  displayName: 'Deploy to IIS Acc'
  dependsOn: Deploy_Dev
  condition: succeeded()

  variables:
  - group: Verix.ContentTower_ACC
  - name: Release.EnvironmentName
    value: 'Acceptance'

  jobs:
  - deployment: DeployToIisAcc
    displayName: 'Deploy Web API to IIS Acc'
    environment:
      name: 'Acceptance'
      resourceType: VirtualMachine
      tags: "internal"

    strategy:
      runOnce:
        deploy:
          steps:
          - powershell: |
              Remove-Item "$(Pipeline.Workspace)\$(artifactName)" -Recurse -Force -ErrorAction SilentlyContinue
            displayName: 'Clean downloaded artifact folder'

          - download: current
            artifact: '$(artifactName)'

          - task: IISWebAppManagementOnMachineGroup@0
            displayName: 'Ensuring IIS Website'
            inputs:
              IISDeploymentType: 'IISWebsite'
              ActionIISWebsite: 'CreateOrUpdateWebsite'
              WebsiteName: '$(iisSiteName)'
              WebsitePhysicalPath: '$(iisPhysicalPath)'
              WebsitePhysicalPathAuth: 'WebsiteUserPassThrough'
              AddBinding: true
              Bindings: |
                $(iisBindings)
              CreateOrUpdateAppPoolForWebsite: true
              AppPoolNameForWebsite: '$(iisAppPoolName)'
              DotNetVersionForWebsite: 'No Managed Code'
              PipeLineModeForWebsite: 'Integrated'
              AppPoolIdentityForWebsite: 'ApplicationPoolIdentity'

          - task: IISWebAppDeploymentOnMachineGroup@0
            displayName: 'Deploy files to IIS'
            inputs:
              WebSiteName: '$(iisSiteName)'
              Package: '$(Pipeline.Workspace)/$(artifactName)/**/*.zip'
              TakeAppOfflineFlag: true
              XmlTransformation: true
              XmlVariableSubstitution: true
              JSONFiles: |
                **/appsettings.json

- stage: Deploy_Prd
  displayName: 'Deploy to IIS Prd'
  dependsOn: Deploy_Acc
  condition: succeeded()

  variables:
  - group: Verix.ContentTower_PRD
  - name: Release.EnvironmentName
    value: 'Production'

  jobs:
  - deployment: DeployToIisPrd
    displayName: 'Deploy Web API to IIS Prd'
    environment:
      name: 'Production'
      resourceType: VirtualMachine
      tags: "internal"

    strategy:
      runOnce:
        deploy:
          steps:
          - powershell: |
              Remove-Item "$(Pipeline.Workspace)\$(artifactName)" -Recurse -Force -ErrorAction SilentlyContinue
            displayName: 'Clean downloaded artifact folder'

          - download: current
            artifact: '$(artifactName)'

          - task: IISWebAppManagementOnMachineGroup@0
            displayName: 'Ensuring IIS Website'
            inputs:
              IISDeploymentType: 'IISWebsite'
              ActionIISWebsite: 'CreateOrUpdateWebsite'
              WebsiteName: '$(iisSiteName)'
              WebsitePhysicalPath: '$(iisPhysicalPath)'
              WebsitePhysicalPathAuth: 'WebsiteUserPassThrough'
              AddBinding: true
              Bindings: |
                $(iisBindings)
              CreateOrUpdateAppPoolForWebsite: true
              AppPoolNameForWebsite: '$(iisAppPoolName)'
              DotNetVersionForWebsite: 'No Managed Code'
              PipeLineModeForWebsite: 'Integrated'
              AppPoolIdentityForWebsite: 'ApplicationPoolIdentity'

          - task: IISWebAppDeploymentOnMachineGroup@0
            displayName: 'Deploy files to IIS'
            inputs:
              WebSiteName: '$(iisSiteName)'
              Package: '$(Pipeline.Workspace)/$(artifactName)/**/*.zip'
              TakeAppOfflineFlag: true
              XmlTransformation: true
              XmlVariableSubstitution: true
              JSONFiles: |
                **/appsettings.json
